### ISSUE TITLE
Cleanup db/* references in smrt-server-analysis

### ISSUE THREAD

**Issue by jfalkner** [PacificBiosciences/smrtflow#58]
CC @mpkocher @skinner 

Split out from this comment https://github.com/PacificBiosciences/smrtflow/issues/55#issuecomment-219853372. It seems we have some hard-coded path logic related to using an sqlite db.

Run the code with the below or directly from IntelliJ.

```bash
sbt smrt-server-analysis/assembly
cd smrt-server-analysis
mkdir db
java -jar target/scala-2.11/smrt-server-analysis*.jar
```

Output will error with similar to the following.

```bash
Connected to the target VM, address: '127.0.0.1:57556', transport: 'socket'
Warning. Assuming relative path /Users/jfalkner/tokeep/git/PacificBiosciences/smrtflow/jobs-root
[WARNING] Unable to load CMD template from pb-engine.pb-cmd-template Error No configuration setting found for key 'pb-engine.pb-cmd-template'
org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:sqlite:db/analysis_services.db) for user '': path to 'db/analysis_services.db': '/Users/jfalkner/tokeep/git/PacificBiosciences/smrtflow/db' does not exist
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:407)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:365)
	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1314)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
	at com.pacbio.secondary.smrtlink.actors.JobsDao.initializeDb(JobsDao.scala:935)
	at com.pacbio.secondary.smrtserver.appcomponents.SecondaryApi$class.startup(SecondaryAnalysisApp.scala:49)
	at com.pacbio.secondary.smrtserver.appcomponents.SecondaryAnalysisServer$.startup(SecondaryAnalysisApp.scala:67)
	at com.pacbio.common.app.BaseApi$ServiceActor.preStart(BaseSmrtServerApp.scala:140)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
	at com.pacbio.common.services.package$RoutedHttpService.aroundPreStart(package.scala:169)
	at akka.actor.ActorCell.create(ActorCell.scala:580)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.sql.SQLException: path to 'db/analysis_services.db': '/Users/jfalkner/tokeep/git/PacificBiosciences/smrtflow/db' does not exist
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:117)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:66)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:21)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:404)
	... 20 more
```

**Comment by skinner** [comment]
Just to clarify, you're seeing that FlywayException backtrace when you don't do _exactly what I wrote_.  Right?

The default JDBC uri in `application.conf` points to an sqlite file in a `db` directory (with a relative path).  Since it's in a conf file, I wouldn't call it "hard-coded"; it gets overridden in production.  I think it's totally reasonable to have a default db location that we use for dev purposes.

I'm not sure what alternative @mpkocher has in mind.  Now that we're in git we could just add the `db` directory under smrt-server-analysis (since perforce doesn't record the existence of empty directories, it wasn't in the perforce repo).  That's my impulse.  Or we could just remove `db/` from the default JDBC uri, maybe?

**Comment by jfalkner** [comment]
> Just to clarify, you're seeing that FlywayException backtrace when you don't do exactly what I wrote. Right?

I'll rerun with your exact instructions and post a followup. I didn't copy it from before, but I think it still errors with a different `FlyWheel` exception related to not finding a sqlitedb.
